tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
brew "cask"
brew "curl"
brew "gh"
brew "node@14", link: true
brew "openssl"
brew "readline"
brew "terraform"
brew "watchman"
brew "berglas"
cask "monodraw"
cask "suspicious-package"
cask "visual-studio-code"
cask "google-cloud-sdk"
