tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
brew "cask"
brew "curl"
brew "gh"
brew "node@16", link: true
brew "openssl"
brew "readline"
brew "watchman"
cask "monodraw"
cask "suspicious-package"
cask "visual-studio-code"
cask "1password/tap/1password-cli"
